### ISSUE TITLE
Missing&Unexpected key(s) in state_dict

### ISSUE THREAD

**Issue by RunpuWei** [dsaragih/diffuse-gen#1]
Hello, thank you for such a wonderful job. However, I faced some problems. When I used the full model you provided to sample the image, it reported an error of Missing&Unexpected key(s) in state_dict
![微信截图_20240109002953](https://github.com/dsaragih/diffuse-gen/assets/36250999/ebaec47e-0da5-43d1-a45c-3ffa42be99f3)

Could you tell me how to solve it?

**Comment by dsaragih** [comment]
Hi, thanks for the interest as this is my first project of this kind. I can't be too sure, but I recall I used ``"attention_resolutions": "32,16,8"`` for the Full Model. I suggest changing this setting around Line 60 of image_editor.py and see how it goes. Otherwise, try the cluster models just to see if this is a larger issue with model loading 👍

**Comment by ssqrots** [comment]
Hello, I am currently facing the same bug as you. Do you have any good solutions? Thank you!

**Comment by RunpuWei** [comment]
> Hello, I am currently facing the same bug as you. Do you have any good solutions? Thank you!

I vaguely remember that perhaps  I didn't run this code successfully
